# Generated by Django 3.0.5 on 2021-05-30 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Userdetails', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
