# Generated by Django 3.2.3 on 2021-06-05 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userdetails', '0009_alter_users_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.TextField(blank=True, max_length=500)),
                ('content', models.TextField(blank=True, max_length=500)),
            ],
        ),
    ]
