# Generated by Django 3.2.3 on 2021-06-06 14:40

from django.db import migrations, models
import django.db.models.aggregates


class Migration(migrations.Migration):

    dependencies = [
        ('Userdetails', '0010_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='sum',
            field=models.ImageField(blank=True, max_length=200, upload_to=''),
        ),
        migrations.AlterField(
            model_name='posts',
            name='content',
            field=models.TextField(blank=True, max_length=django.db.models.aggregates.Max),
        ),
    ]
