# Generated by Django 3.2.3 on 2021-06-07 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userdetails', '0013_alter_posts_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=50)),
                ('about', models.TextField(blank=True, max_length=500)),
                ('profimg', models.ImageField(blank=True, upload_to='proimage')),
                ('Twitter', models.URLField(default='#')),
                ('insta', models.URLField(default='#')),
                ('face', models.URLField(default='#')),
                ('pin', models.URLField(default='#')),
            ],
        ),
        migrations.AddField(
            model_name='posts',
            name='Image',
            field=models.ImageField(blank=True, upload_to='image'),
        ),
    ]
