# Generated by Django 3.2.3 on 2021-06-07 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Userdetails', '0014_auto_20210607_1121'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminU',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='Image',
        ),
    ]
